/**
 * 工具环境变量管理服务
 * 
 * 职责：
 * 1. 管理工具的环境变量配置（.env 文件）
 * 2. 加载环境变量到工具执行环境
 * 3. 支持 configure 模式更新配置
 */

import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import { logger } from '../utils/logger.js';
import { pathExists } from './tool-utils.js';

/**
 * 加载工具环境变量
 * @param {string} toolName - 工具名称
 * @returns {object} 环境变量对象
 */
export async function loadToolEnvironment(toolName) {
  const toolDir = path.join(os.homedir(), '.prompt-manager', 'toolbox', toolName);
  const envFilePath = path.join(toolDir, '.env');
  
  // 检查 .env 文件是否存在
  if (!await pathExists(envFilePath)) {
    logger.debug(`工具 ${toolName} 的 .env 文件不存在`);
    return {};
  }
  
  try {
    // 读取 .env 文件内容
    const envContent = await fs.readFile(envFilePath, 'utf-8');
    
    // 解析 .env 文件内容
    const envVars = {};
    const lines = envContent.split('\n');
    
    for (const line of lines) {
      // 跳过注释和空行
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith('#')) {
        continue;
      }
      
      // 解析键值对
      const equalIndex = trimmedLine.indexOf('=');
      if (equalIndex === -1) {
        continue;
      }
      
      const key = trimmedLine.substring(0, equalIndex).trim();
      let value = trimmedLine.substring(equalIndex + 1).trim();
      
      // 处理带引号的值
      if ((value.startsWith('"') && value.endsWith('"')) || 
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.substring(1, value.length - 1);
      }
      
      // 处理转义字符
      value = value.replace(/\\n/g, '\n').replace(/\\t/g, '\t');
      
      // 尝试解析JSON（如果是JSON数组或对象）
      try {
        if ((value.startsWith('[') && value.endsWith(']')) || 
            (value.startsWith('{') && value.endsWith('}'))) {
          const parsed = JSON.parse(value);
          envVars[key] = parsed;
        } else {
          envVars[key] = value;
        }
      } catch {
        // 不是有效的JSON，直接使用字符串值
        envVars[key] = value;
      }
    }
    
    logger.debug(`工具 ${toolName} 环境变量加载成功`, { 
      count: Object.keys(envVars).length 
    });
    
    return envVars;
    
  } catch (error) {
    logger.error(`加载工具 ${toolName} 的环境变量失败`, { error: error.message });
    return {};
  }
}

/**
 * 保存工具环境变量配置
 * @param {string} toolName - 工具名称
 * @param {object} envVars - 环境变量对象
 */
export async function saveToolEnvironment(toolName, envVars) {
  const toolDir = path.join(os.homedir(), '.prompt-manager', 'toolbox', toolName);
  await fs.ensureDir(toolDir);
  
  const envFilePath = path.join(toolDir, '.env');
  
  // 读取现有配置（如果存在）
  const existingVars = await loadToolEnvironment(toolName);
  
  // 合并配置
  const mergedVars = {
    ...existingVars,
    ...envVars
  };
  
  // 生成 .env 文件内容
  let envContent = `# Tool Environment Variables
# Tool: ${toolName}
# Generated by PromptManager ToolEnvironment
# Last modified: ${new Date().toISOString()}

`;
  
  // 写入环境变量
  for (const [key, value] of Object.entries(mergedVars)) {
    let escapedValue;
    
    // 如果值是对象或数组，转换为JSON字符串
    if (typeof value === 'object' && value !== null) {
      escapedValue = JSON.stringify(value);
    } else {
      // 转义特殊字符
      escapedValue = String(value)
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n')
        .replace(/\t/g, '\\t');
    }
    
    // 如果值包含空格、等号或特殊字符，用引号包裹
    if (escapedValue.includes(' ') || escapedValue.includes('=') || escapedValue.includes('[') || escapedValue.includes('{')) {
      escapedValue = `"${escapedValue}"`;
    }
    
    envContent += `${key}=${escapedValue}\n`;
  }
  
  // 写入文件
  await fs.writeFile(envFilePath, envContent, 'utf-8');
  
  logger.info(`工具 ${toolName} 环境变量配置已保存`, { 
    count: Object.keys(mergedVars).length 
  });
}

/**
 * 获取工具环境变量配置信息
 * @param {string} toolName - 工具名称
 * @param {object} schema - 工具的环境变量Schema
 * @returns {object} 配置信息对象
 */
export async function getToolEnvironmentInfo(toolName, schema) {
  const toolDir = path.join(os.homedir(), '.prompt-manager', 'toolbox', toolName);
  const envFilePath = path.join(toolDir, '.env');
  
  // 加载当前配置
  const currentVars = await loadToolEnvironment(toolName);
  
  // 获取环境变量定义
  const envProps = schema?.environment?.properties || {};
  
  // 构建配置信息
  const configured = [];
  const unconfigured = [];
  
  for (const [key, def] of Object.entries(envProps)) {
    const value = currentVars[key];
    const defaultValue = def.default;
    
    if (value !== undefined) {
      configured.push({
        key,
        value,
        description: def.description || '',
        status: '✅ 已配置'
      });
    } else {
      unconfigured.push({
        key,
        defaultValue,
        description: def.description || '',
        status: '⚠️ 使用默认值'
      });
    }
  }
  
  return {
    toolName,
    envFilePath,
    configured,
    unconfigured,
    hasConfig: await pathExists(envFilePath)
  };
}

